export { default as addItemToOrderMutation } from './mutations/addItemToOrder.gql'
export { default as currentOrderQuery } from './queries/currentOrder.gql'
export { default as closeOrderMutation } from './mutations/closeOrder.gql'
export { default as ordersQuery } from './queries/orders.gql'
export { default as orderQuery } from './queries/order.gql'
