query FetchOrder ($id: String!) {
  order(id: $id){
    table {
      bar {
        name
      }
    },
    items {
      id,
      quantity,
      menuItem {
        name,
        price
      }
    }
  }
}