query FetchMenuItem ($id:String!){
  menuItem(id:$id) {
    id,
    name,
    price,
    photo,
    waitingTime,
    description,
    peopleCount,
    menuCategory {
      bar {
        id,
        status
      }
    }
  }
}